import matplotlib.pyplot as plt
import numpy as np

print('-'*50 + '\n' + 'Visualisasi Data Sederhana'.center(50) + '\n' + '-'*50)
print('[1]. Line Plot')
print('[2]. Scatter Plot')
print('[3]. Bar Plot')
print('[4]. Keluar Program')
print('-'*50)
print('Peraturan: ')
print("- Silahkan pilih no. 1 s/d 3 untuk plot dan 4 untuk keluar")
print("- Isi nilai x dan y dengan menggunakan: [.., .., .., dst]")
print("- Isi nilai x dan y dengan jumlah yang sama dan berurutan")
print("- Contoh isi nilai x/y bertipe angka: [1, 2, 3, .., .., dst]")
print("- Contoh isi nilai x/y bertipe huruf: ['a', 'b', 'c', .., 'dst']")
print('-'*50 + '\n')

while True:
    nomor = int(input('Silahkan pilih nomor pada daftar: '))
    if nomor == 1:
        x = input('Masukkan nilai x: ')
        y = input('Masukkan nilai y: ')
        ket_x = input('Masukkan keterangan sumbu x: ')
        ket_y = input('Masukkan keterangan sumbu y: ')
        ttl = input('Masukkan judul: ')
        x = np.array(eval(x))
        y = np.array(eval(y))
        print('\n')
        plt.plot(x, y)
        plt.title(ttl)
        plt.xlabel(ket_x)
        plt.ylabel(ket_y)
        plt.show()
    if nomor == 2:
        x = input('Masukkan nilai x: ')
        y = input('Masukkan nilai y: ')
        ttl = input('Masukkan judul: ')
        ket_x = input('Masukkan keterangan sumbu x: ')
        ket_y = input('Masukkan keterangan sumbu y: ')
        x = np.array(eval(x))
        y = np.array(eval(y))
        print('\n')
        plt.scatter(x, y)
        plt.title(ttl)
        plt.xlabel(ket_x)
        plt.ylabel(ket_y)
        plt.show()
    if nomor == 3:
        x = input('Masukkan nilai x: ')
        y = input('Masukkan nilai y: ')
        ttl = input('Masukkan judul: ')
        ket_x = input('Masukkan keterangan sumbu x: ')
        ket_y = input('Masukkan keterangan sumbu y: ')
        x = np.array(eval(x))
        y = np.array(eval(y))
        print('\n')
        plt.bar(x, y)
        plt.title(ttl)
        plt.xlabel(ket_x)
        plt.ylabel(ket_y)
        plt.show()
    if nomor == 4:
        print('Anda telah keluar dari Program\nSilahkan masuk kembali')
        exit()
